<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MailIntelligenceLab.Core\MailIntelligenceLab.Core.csproj" />
    <ProjectReference Include="..\MailIntelligenceLab.Adapters\MailIntelligenceLab.Adapters.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
